# Generated by Django 3.0.5 on 2020-04-19 08:49

import clfapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False, verbose_name='model id')),
                ('model_name', models.CharField(max_length=30, unique=True, verbose_name='model name')),
                ('model_upload', models.FileField(upload_to='models/', verbose_name='upload models')),
                ('model_desc', models.CharField(max_length=100, verbose_name='model desc')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, verbose_name='user id')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='user name')),
            ],
        ),
        migrations.CreateModel(
            name='Uploadfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=clfapp.models.user_directory_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clfapp.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_cut_id', models.IntegerField(verbose_name='word cut id')),
                ('clf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classficer', to='clfapp.Models')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clfapp.Users')),
                ('vec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vectorizer', to='clfapp.Models')),
            ],
        ),
    ]
